### ISSUE TITLE
upload failed. Please check your internet connection.

### ISSUE THREAD

**Issue by fengcen** [nonoroazoro/vscode-syncing#1]
My network is ok. I try uploading with/without proxy. It always complains this problem. Another extension [shanalikhan/code-settings-sync](https://github.com/shanalikhan/code-settings-sync) works fine.

**Comment by nonoroazoro** [comment]
@fengcen  Sorry about that.
Could you please help to check if there's any related logs in `Developer Tools` (via Menu -> Help -> Developer Tools).
And then, if possible, May I check your **proxy settings**.

P.S. I'll add a simple logging system in the next release. Sorry for the inconvenience.

**Comment by fengcen** [comment]
vscode version: 1.8.1

I debug the extension and found the error:
```
{"message":"Invalid request.\n\nFor 'properties/content', nil is not a string.","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}
```

**Comment by nonoroazoro** [comment]
@fengcen  Thanks! I find out that it's an error from **node-github**'s api, I'll solve the bug in the next update.

**Comment by nonoroazoro** [comment]
@fengcen I've fixed and updated the extension, please check, Thanks!

**Comment by fengcen** [comment]
@nonoroazoro It works. Thank you.
