### ISSUE TITLE
CursorAI support

### ISSUE THREAD

**Issue by tribbloid** [nonoroazoro/vscode-syncing#103]
### Specifications

* OS Version: Pop_OS 22.04

* VSCode Version: CursorAI

### Expected Behavior

can sync with a predetermined VSCCode edition

### Actual Behavior

![image](https://github.com/user-attachments/assets/d8dbec4a-3f39-4b02-9266-c70238979163)

### Steps to Reproduce

1. in CursorAI, enable this pluging

2. download settings

**Comment by tribbloid** [comment]
I wonder if there is a workaround that can make CursorAI to fake as VSCode-stable

**Comment by nonoroazoro** [comment]
Supported in latest release v3.3.8~
