### ISSUE TITLE
add autosyncing

### ISSUE THREAD

**Issue by volosovich** [nonoroazoro/vscode-syncing#14]
Hi
Please add autosyncing option or some reminder for syncing.
Cool idea is  - checking if new version on gist is newer than local version - auto-download settings from gist. Upload only manual.

**Comment by nonoroazoro** [comment]
@volosovich Thanks! An indicator is a good idea, but the auto-synchronization may not be as easy as it seems (Please refer to #6) and I can not promise anything. I'm sorry.
