### ISSUE TITLE
你好 希望加入自动同步功能

### ISSUE THREAD

**Issue by cuipengcx** [nonoroazoro/vscode-syncing#15]
## Specifications

* OS Version:
* VSCode Version:

## Steps to Reproduce

1.
1.
1.

**Comment by nonoroazoro** [comment]
@cuipengcx 关于这个功能的讨论请参考 #6。

总结一下就是：

1. VSCode 本身并没有提供监控配置文件修改状态的 API（实际上官方团队根本不赞成用插件来管理配置文件），因此只能用 node 来监控，但我认为并不优雅。

1. 自动上传最大的缺陷：假设你想尝试一些新的插件、或者新的配置，修改完毕后都会被自动上传，哪怕这些配置你并不想继续用了。除非你知道如何修改 Gist，否则没人知道怎么回退。当然如果我为 Syncing 增加版本回退功能也可以做到，但是这样这个插件就太复杂了，违背我设计的初衷。

所以在有更好的办法之前，我不会增加这个功能，抱歉。当然你可以尝试一下 [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)，他有提供自动同步。

**Comment by imhuay** [comment]
那能否根据文件的修改日期做一下简单的提醒，
有时在一台设备上修改上传后，时间一长就忘了，在另一台设备上没有下载新配置，又上传了别的修改；把之前的修改覆盖了

**Comment by nonoroazoro** [comment]
@imhuay 恩，我觉得这个可以有！提示一下是本地还是远程版本更新。等下个版本吧~
