### ISSUE TITLE
Extensions won't sync when disabled?

### ISSUE THREAD

**Issue by mastrauckas** [nonoroazoro/vscode-syncing#17]
## Specifications

* OS Version: mac

* VSCode Version: 1.18.0-insider

## Expected Behavior
Expect extensions to sync when disabled(always or workspace) and keep their disable state when downloading settings later.

## Actual Behavior
Disabled extensions are not synced.

## Steps to Reproduce

1. Disable an extension(always or workspace)

2. Upload Settings

3. View gist and it does not upload settings that are disabled.

**Comment by nonoroazoro** [comment]
Due to the limitation of VSCode API, it's not possible to detect the disabled extensions yet. Sorry.

**Comment by mastrauckas** [comment]
So it only tells you enabled extensions and not installed extensions?

**Comment by nonoroazoro** [comment]
@mastrauckas That's right, but I'll add this feature as soon as VSCode API is updated.
