### ISSUE TITLE
Extensions would not be downloaded

### ISSUE THREAD

**Issue by mubaidr** [nonoroazoro/vscode-syncing#18]
## Specifications

* OS Version: Windows 10

* VSCode Version: 1.17 update: Also tried the insiders build but same

## Expected Behavior
Extensions should be downloaded

## Actual Behavior
Settings downloaded, but extensions are not installed

## Steps to Reproduce

1. I have absolutely no idea. :( Help me debug this issue. It shows syncing progress (and installing extension progress) but none of them is actually installed. Where can i find log? (there is no message or error in developer tools)

I am behind proxy server if this is of any help but this should be issue as settings download works and manually installing extensions also works.

**Comment by nonoroazoro** [comment]
@mubaidr Usually the extensions are located in `%userprofile%\.vscode\extensions`, and if the extensions are successfully downloaded, you shall find them there.

I guess maybe `Syncing` has no privileges to access the extensions folder (`%userprofile%\.vscode\extensions`), but I'm not sure about it casue the progress indicator of `Syncing` shows no error...

**Comment by mubaidr** [comment]
Yes, i am checking the same folder, if i install any extension manual it appears in that folder. Two of my pc works good with this extension, only one has issue.

Only thing different between them is proxy server for the Internet, but again manual downloading and vs-code update works fine. 

This is driving me nuts, i had to install ~40 extensions manually one by one. Hope I could help you solve this. 

I will definitely try without UAC and report back.

**Comment by nonoroazoro** [comment]
@mubaidr I suggest you could copy all of the 40 extensions to the pc which went wrong.

**Comment by stopanko** [comment]
@mubaidr  Had the same problem.
I have closed VsCode. After i chose Syncing -> Download settings. It will stop on the first extention. 
I have installed it manually and after rerun Syncing. IT stops only on several extentions. Do the same for each

**Comment by nonoroazoro** [comment]
@stopanko The reason that the extensions are downloaded again is because the previous synchronization is not correctly finished. I think you may try the following steps:

1. Clear your VSCode extensions dir:

    1. Windows: `%userprofile%\.vscode\extensions`

    1. Mac: `~/.vscode/extensions`

2. Check your proxy settings in VSCode settings: `http.proxy` (cause currently the `http_proxy` and `https_proxy` are not taken from your environment variables, Syncing only read the VSCode http settings for now).

**Comment by mubaidr** [comment]
I believe this is related to: https://github.com/Microsoft/vscode/issues/69

**Comment by nonoroazoro** [comment]
@mubaidr Thanks a lot!
