### ISSUE TITLE
下载配置的时候，卡死

### ISSUE THREAD

**Issue by aQuaYi** [nonoroazoro/vscode-syncing#19]
## Specifications

* OS Version:
Ubuntu 16.04.2
* VSCode Version:
1.17.2
## Expected Behavior
正常下载配置

## Actual Behavior
下载配置的时候卡死了，显示以下信息
![syncing](https://user-images.githubusercontent.com/6028869/31999930-90324e70-b9c7-11e7-96fc-dde8b5707703.png)

我在插件栏，搜索了 这个插件，发现没有被安装。就手动安装了一下，再次下载配置就好了。
但是实际上，在下载配置前，我肯定安装了这个插件了的。

PS：刚刚我又测试了一下，会随机地卡死在某个插件。我在插件栏搜索那个插件的话，会显示为未安装。

PS2：刚刚我还测试了一下，上传后，马上下载，很顺利。所以，我猜想，是不是 remote 的插件版本号比  local 的低的时候，会重新下载安装。

**Comment by nonoroazoro** [comment]
@aQuaYi 是的，插件会同步**精确版本**。

不过`卡死`不应该出现的。我想知道精确描述，这里的`卡死`是指进度条再也不动了，后续插件也都没装上去，还是什么状况？

**Comment by aQuaYi** [comment]
![syncing](https://user-images.githubusercontent.com/6028869/31999930-90324e70-b9c7-11e7-96fc-dde8b5707703.png)
@nonoroazoro 卡死的意思是 VSCode 的状态栏一直呈现，上图中的样子
其中图中 "[1/5]" 左边的贪食蛇一直在转圈圈。

**Comment by aQuaYi** [comment]
@nonoroazoro  我刚刚试了一下在 gist.github.com 把某个插件的版本号改小，然后再下载配置。
可是，还是成功了，没有卡死。所以，我猜想，这个问题也可能和我的网络环境有关。

不过，版本号不同，就删除插件重装是必须的吗？插件的具体版本，可以由插件系统来负责的呀。

**Comment by nonoroazoro** [comment]
@aQuaYi 我估计和网络关系比较大的 😸 

关于版本问题，之所以同步精确版本，是因为当初考虑了几个地方：

1. 有些时候需要特定版本的插件，而非最新版本。*这个原因是由工作环境导致的，新版本插件有时候反而无法工作，而在 VSCode Marketplace 中想要回滚版本是比较困难的。*

1. 早期 VSCode 并没有`自动升级插件`的功能，假设我有 2 台设备，A 设备已经手动更新至最新版，那么在用 Syncing 同步到 B 设备上时，是不能自动升级至最新版的（因为没有精确同步版本号），需要手动更新。

这个**精确同步**就像鱼和熊掌不能兼得一样。。。

**Comment by nonoroazoro** [comment]
@aQuaYi 如果没有问题的话，我就关掉啦。
