### ISSUE TITLE
Why not restore the settings and keybindings first?

### ISSUE THREAD

**Issue by fengcen** [nonoroazoro/vscode-syncing#2]
If you restore the settings and keybindings first, I do not need to manually set up the proxy.

**Comment by nonoroazoro** [comment]
@fengcen In fact, the settings and keybinding are now the first to sync.

But in the very beginning, when you download/upload settings, there is no proxy setting in your local settings file, unless you have set up one.

Thus, there's no way to avoid this manually set up.
