### ISSUE TITLE
Feature request: Stupidity protection

### ISSUE THREAD

**Issue by christianmalek** [nonoroazoro/vscode-syncing#25]
Hi @nonoroazoro !
I really like your extension. It's working great!

But I think it's way too easy to overwrite the synced data by accident. I use VS Code with your extension on at least two different devices and the first time I wanted to sync them I deleted the settings from one because I didn't use your extension properly. It would be cool if your extension could check the amount of changes and asks the user if they really want to upload on the specific gist or if they want to sync on a new gist.

**Comment by nonoroazoro** [comment]
@christianmalek Thank you for your feedback. It's a good idea and I'll consider introducing this feature.

**Comment by nonoroazoro** [comment]
@christianmalek I've release the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/tag/v1.6.0)) for this feature, enjoy!

**Comment by christianmalek** [comment]
I'll check it out. Thanks for your awesome work!
