### ISSUE TITLE
一直显示syncing checking remote gists

### ISSUE THREAD

**Issue by zengcanxiang** [nonoroazoro/vscode-syncing#27]
## Specifications

* OS Version:
linux deepin 15.5
* VSCode Version:
1.21
## Expected Behavior
设置成功

## Actual Behavior
长时间显示checking remote gists

## Steps to Reproduce
本地代理已经开启，能够翻墙，http_proxy也设置了，不过，设置文件里id和token没有填。

1.打开命令行，输入sync uploadsetting

2. 输入gists token

3.左下角显示checking,长时间等待也无法成功

**Comment by nonoroazoro** [comment]
上传的话，需要填写 Token，否则不会进行上传。

同时如果不填写 Token，是不会去 checking 的，本地就直接停止后续步骤了。所以你能再确认一下复现过程吗？

如果你已经填了 Token，出现长时间 checking，通常就是网络问题，你可以试试不填写任何代理配置，尝试几次看看能不能访问到 GitHub Gist。

**Comment by zengcanxiang** [comment]
我是在ctrl+p的命令面板里填了token,在文件中没有填写token....我尝试一下在文件中也填写token

**Comment by nonoroazoro** [comment]
不需额外在文件中填写。。。你只要在 Ctrl + P 之后按照提示填写就可以了，Syncing 会自动记录。
