### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by johnpyp** [nonoroazoro/vscode-syncing#28]
Wow, this is such an amazing extension. It has literally saved my life working on so many machines. I'd like to donate a couple coffees worth (not nearly enough) to you for working and continuing development, how can I do that?

Thanks for this amazing tool :)

**Comment by nonoroazoro** [comment]
@johnpyp I'm so glad that you like this extension! The fact is I made it just for fun :) and I never think about taking any donation~

And don't worry, it's for sure that I will keep working and try my best to keep it simple and reliable. :smile_cat:
