### ISSUE TITLE
Settings exclude

### ISSUE THREAD

**Issue by i4004** [nonoroazoro/vscode-syncing#29]
It is possible to exclude some settings from sync?

For example i want to exclude http.proxy (this is used by extensions installer etc.) and "workbench.colorTheme" settings. Because they are different on different machines.

**Comment by nonoroazoro** [comment]
I' sorry there's no such feature yet...

**Comment by nonoroazoro** [comment]
@i4004 I've added this feature, and I will release it after the test :smile:

**Comment by nonoroazoro** [comment]
@i4004 I've release the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/tag/v1.6.0)) for this feature, enjoy!
