### ISSUE TITLE
Upload the pretty extensions.json

### ISSUE THREAD

**Issue by fengcen** [nonoroazoro/vscode-syncing#3]
Advantages:
1. You can easily know the diff of extensions.
2. Sometimes I have to manually install extensions. Pretty extensions.json can save some time.

**Comment by nonoroazoro** [comment]
@fengcen Thanks very much! I will consider it. 😸

**Comment by nonoroazoro** [comment]
Finished in https://github.com/nonoroazoro/vscode-syncing/commit/155bb02a9e713fa12856ba1981f19211d5f6e7fb.

You can find it in the latest release. 😸
