### ISSUE TITLE
Download is very slow, compared to my manual download.

### ISSUE THREAD

**Issue by yuxing1994** [nonoroazoro/vscode-syncing#30]
![image](https://user-images.githubusercontent.com/19182789/39408517-1c9d9c46-4c0a-11e8-9dd4-1034f066e6a3.png)
I manually download or another type of plug-in download is much faster than this one, this plug-in is basically downloaded, why??

**Comment by yuxing1994** [comment]
Keep circling

**Comment by nonoroazoro** [comment]
@yuxing1994 检查一下是不是设置了代理？

**Comment by yuxing1994** [comment]
ANT_HOME=/usr/share/apache-ant
AUTOJUMP_ERROR_PATH=/home/yuxing1994/.local/share/autojump/errors.log
AUTOJUMP_SOURCED=1
CLASSPATH=.:/usr/lib/jvm/default/lib/dt.jar:/usr/lib/jvm/default/lib/tools.jar
COLORFGBG=15;0
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=/usr/share/xsessions/plasma
DISPLAY=:0
GRADLE_HOME=/usr/share/java/gradle
GS_LIB=/home/yuxing1994/.fonts
GTK_IM_MODULE=fcitx
GTK_MODULES=canberra-gtk-module
HOME=/home/yuxing1994
JAVA_HOME=/usr/lib/jvm/default
JRE_HOME=/usr/lib/jvm/default/jre
KDED_STARTED_BY_KDEINIT=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
KONSOLE_DBUS_SERVICE=:1.43
KONSOLE_DBUS_SESSION=/Sessions/1
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_PROFILE_NAME=配置方案 1
LANG=zh_CN.UTF-8
LANGUAGE=
LESS=-R -i -g -c -W
LOGNAME=yuxing1994
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/spool/mail/yuxing1994
MAVEN_OPTS=-Xmx512m
OLDPWD=/home/yuxing1994/yx/www
PAGER=less
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PATH=/usr/lib/jvm/default/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/last-working-dir:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/autojump:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/home/yuxing1994/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/yuxing1994/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/yuxing1994/.antigen/bundles/zsh-users/zsh-autosuggestions:/home/yuxing1994/.antigen/bundles/zsh-users/zsh-completions:/home/yuxing1994/.antigen/bundles/zsh-users/zsh-history-substring-search
PROFILEHOME=
PWD=/home/yuxing1994/yx/www
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_IM_MODULE=fcitx
SESSION_MANAGER=local/archlinux:@/tmp/.ICE-unix/550,unix/archlinux:/tmp/.ICE-unix/550
SHELL=/bin/zsh
SHELL_SESSION_ID=fdcde1478976410d8304ea418ec1917d
SHLVL=2
TERM=screen-256color
TMUX=/tmp//tmux-1000/default,1522,3
TMUX_PANE=%3
USER=yuxing1994
XAUTHORITY=/home/yuxing1994/.Xauthority
XCURSOR_THEME=breeze_cursors
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=c1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=1
XMODIFIERS=@im=fcitx
_=/bin/env
LESSOPEN=|/usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
LESS_TERMCAP_mb=[01;31m
LESS_TERMCAP_md=[01;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[01;44;33m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[01;32m
LC_CTYPE=zh_CN.UTF-8

**Comment by yuxing1994** [comment]
syning.json :    "http_proxy": ""
