### ISSUE TITLE
Syncing should not sync the "proxy" setting

### ISSUE THREAD

**Issue by asnowfix** [nonoroazoro/vscode-syncing#32]
### Specifications

* OS Version: all

* VSCode Version: latest

### Expected Behavior

Syncing does to sync the proxy settings:

```json
  // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
  "http.proxy": "",

  // The value to send as the 'Proxy-Authorization' header for every network request.
  "http.proxyAuthorization": null,

  // Whether the proxy server certificate should be verified against the list of supplied CAs.
  "http.proxyStrictSSL": true
```

### Actual Behavior

Syncing syncs everything

### Steps to Reproduce

1.  Make vscode settings changes on a machines behind a proxy
1.  Syncing-upload
1.  Syncing-download on machine NOT behind a proxy
1.  machine NOT behind a proxy can no longer access Syncing or any other HTTP resource

The same scenario happens (of course) in the opposite direction.

**Comment by asnowfix** [comment]
As a work-around, I added the following settings, but proxy should really be filtered out by default.

```json
    "syncing.upload.exclude": [
        "http.proxy*",
        "editor.font*",
        "terminal.integrated.font*"
    ],
```

**Comment by nonoroazoro** [comment]
From version `1.5.0` onwards, `Syncing` no longer reads the `http.proxy` from `VSCode User Settings`. In fact, `Syncing` uses its own settings file now.

But If you want to exclude the `http.proxy` setting from being uploaded, you can set glob patterns [here](https://github.com/nonoroazoro/vscode-syncing#vscode-user-settings), which is introduced in `1.6.0`.

**Comment by nonoroazoro** [comment]
@asnowfix Besides, `Syncing` is designed to sync all of the settings, so I don't think it should exclude the proxy settings by default.

**Comment by asnowfix** [comment]
@nonoroazoro well I get the design intention, but take a careful look at the use-case. And BTW, the in-Syncing http proxy setting does work: it does not not circumvent the top-level proxy setting, when set: Syncing fails as soon as top-level http proxy setting is set.

**Comment by nonoroazoro** [comment]
@asnowfix You mentioned the `top-level proxy setting`,  did you mean the `http.proxy` setting of VSCode, or the `http_proxy` (`https_proxy`) setting of your OS environment?

**Comment by nonoroazoro** [comment]
@asnowfix About the proxy settings, here's the priority list (**high-to-low**):

1. Syncing's own settings file (`syncing.json`);
1. The `http_proxy` or `https_proxy` environment variables of your current OS.

Hope this could explain how Syncing reads the proxy setting :).

**Comment by asnowfix** [comment]
@nonoroazoro I meant the VScode setting.

**Comment by nonoroazoro** [comment]
@asnowfix I've checked again, the top-level proxy setting does not affect the synchronization... 😄

**Comment by nonoroazoro** [comment]
@asnowfix If there's no other problem, I'd close this issue.
