### ISSUE TITLE
Sync to a file location instead of a gist

### ISSUE THREAD

**Issue by frankhommers** [nonoroazoro/vscode-syncing#34]
Now that would be a great feature ;-)

**Comment by nonoroazoro** [comment]
Sorry, I'm far too busy recently. It's a good idea, but it seems that there're already such extensions there...

**Comment by frankhommers** [comment]
There aren't already such extension. Only one and that's not working.

**Comment by frankhommers** [comment]
Could you please point me to an extension which does this?

**Comment by nonoroazoro** [comment]
@frankhommers Maybe [sync-rsync](https://marketplace.visualstudio.com/items?itemName=vscode-ext.sync-rsync) could work, but I haven't tried it...

**Comment by frankhommers** [comment]
No. That syncs projects content. Not VS Code settings.

I think you are wrong, there aren't any working extensions that sync settings to a file location.

**Comment by nonoroazoro** [comment]
@frankhommers Thanks for your response! I'll see if there's a proper way to add this feature, but this may take some time :)
