### ISSUE TITLE
Exclude Extensions from Syncing

### ISSUE THREAD

**Issue by mattyuen** [nonoroazoro/vscode-syncing#35]
Hi Nonoroazoro,

As per your latest feature that excludes settings from syncing, is it possible to do the same for extensions?

**Comment by nonoroazoro** [comment]
@mattyuen Sorry, I'm far too busy recently. I will consider adding this feature, but still not for sure~ Thanks for your good idea.

**Comment by nonoroazoro** [comment]
Hi @mattyuen , after some digging, I think probably you should `disable` the extensions to avoid being uploaded. So this feature will not be implemented in the near future.

**Comment by switch-it** [comment]
Thanks @nonoroazoro .
Guess I'll just have to wait for https://github.com/Microsoft/vscode/issues/2743 ... if it ever happens!

**Comment by mattyuen** [comment]
Thanks @nonoroazoro .
Guess I'll just have to wait for https://github.com/Microsoft/vscode/issues/2743 ... if it ever happens!

**Comment by nonoroazoro** [comment]
@mattyuen I'll try my best to find out a solution. :smile:

**Comment by nonoroazoro** [comment]
@mattyuen It's confirmed that this feature will be included in the next release! :smile:

**Comment by nonoroazoro** [comment]
@mattyuen, I've released the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/latest)) for this feature, enjoy!
