### ISSUE TITLE
vscode支持携带版了,能否考虑修改配置文件的路径

### ISSUE THREAD

**Issue by seekwe** [nonoroazoro/vscode-syncing#36]
Windows下 AppData\Roaming\code\User 的路径可以改成 vscode目录的data里吗?

**Comment by nonoroazoro** [comment]
@seekwe 回头我看一下，可能会在后面版本支持自定义路径。

**Comment by nonoroazoro** [comment]
@seekwe 这两天看了一下，携带版的配置目录信息目前还没法简单的通过 api 拿到，我可能会等到官方把这个特性做的更完善一些的时候再动手。目前看来有可能后续会有变动。

**Comment by nonoroazoro** [comment]
@seekwe 很抱歉等了这么久，目前携带版的支持已经完成，测试完毕后下个版本会包含这个功能。

**Comment by nonoroazoro** [comment]
@seekwe 新版本发布了，应该 OK 啦。

**Comment by seekwe** [comment]
> @seekwe 新版本发布了，应该 OK 啦。

辛苦啦
