### ISSUE TITLE
[ Feature request ] Sync between macOS and GNU+Linux

### ISSUE THREAD

**Issue by cig0** [nonoroazoro/vscode-syncing#37]
### Specifications

* OS Version: macOS 10.13.6 and GNU+Linux (NixOS and Ubuntu 18.04)

* VSCode Version: 1.25 (on both systems)

### Expected Behavior
Sync everything between the VS Code living on different platforms!

### Actual Behavior
As you properly point out in the readme, settings for macOS and the rest of the platforms sync separately :( 

//

Quick question: is there any workaround to solve this using Syncing? Thanks!

**Comment by nonoroazoro** [comment]
@cig0 I will release a new version which will merge the settings into one.

**Comment by nonoroazoro** [comment]
@cig0 , I've released the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/tag/v1.7.2)) for this feature, enjoy!

**Comment by cig0** [comment]
Dope!
