### ISSUE TITLE
There is a problem on first time syncing.

### ISSUE THREAD

**Issue by liamwang** [nonoroazoro/vscode-syncing#38]
### Specifications

* OS Version: Win10

* VSCode Version: 1.25.1

### Actual Behavior

两台电脑，插件安装情况基本一样。第一台用 Syncing 插件把配置上传到 GitHub Gist 了。然后用第二台电脑（第一次）从这个Gist下载配置，这时候会把现有安装插件全部清空，包括 Syncing 插件本身。然后需要重新安装 Syncing，重新 Download Gist 配置和安装。

也就是说第一次同步另一台机器的配置时，整个过程先是把所有已安装的插件卸载掉，然后又重新安装一遍，很慢长的等待。

### Expected Behavior

第一次同步另一台机器的配置时，如果本机的插件和Gist上要同步的插件版本一致，则不应该卸载再安装。

### Steps to Reproduce

1. 在第一台机器上配置好Gist，并上传。

2. 在另一台机器上第一次从该Gist下载配置。

**Comment by liamwang** [comment]
好像是我填错Gist ID了，用的是之前的Settings Sync的Gist ID。

**Comment by nonoroazoro** [comment]
@liamwang 搞定就行，哈哈
