### ISSUE TITLE
被禁用的插件不会被上传？

### ISSUE THREAD

**Issue by liaoyinglong** [nonoroazoro/vscode-syncing#40]
### Specifications

* OS Version:
 win10，osx
* VSCode Version: 1.
1.26.1

### Steps to Reproduce

1. 禁用某个插件（非在此工作区禁用）
![1](https://user-images.githubusercontent.com/23382699/44704177-f7aa8d00-aacc-11e8-889c-440d260c3b43.png)

1. upload setting

1. 查看gist发现插件被删除了
![2](https://user-images.githubusercontent.com/23382699/44704184-fc6f4100-aacc-11e8-86a6-d6bbd2b14b53.png)

这是符合预期的吗？

**Comment by nonoroazoro** [comment]
@liaoyinglong 符合预期，因为微软目前没有提供任何检测`已禁用`插件的 API。

**Comment by liaoyinglong** [comment]
好的吧，我前面几次发现在另外一台电脑同步时候丢失插件，当是也没有注意。以为是`gist ID`的问题，今天测试了一下禁用插件，才清楚发生什么事情。
搜索了一下`issues`也没有发现相关内容。

**Comment by nonoroazoro** [comment]
@liaoyinglong 只要官方出了 API，我肯定第一时间加上，嘿嘿。
