### ISSUE TITLE
Fix the diff algorithm

### ISSUE THREAD

**Issue by agross** [nonoroazoro/vscode-syncing#41]
### Specifications

* OS Version: macOS/Windows 10

* VSCode Version: Latest

I often see diffs being generated that are larger than they need to be. For example, I just made a change to a single setting (in the JSON) and uploaded it. VS Code Syncing on Windows generated [a diff that refers to extensions](https://gist.github.com/agross/6011e4a3e9d1c92b3861978c6134db23/revisions#diff-4769e2216318d746f15eec568beffb28) (despite them being unchanged). Just before that, I did the same on the Mac (changed a setting), here also [41 extension-related lines](https://gist.github.com/agross/6011e4a3e9d1c92b3861978c6134db23/revisions#diff-4769e2216318d746f15eec568beffb28) were changed for no obvious reason.

### Expected Behavior

Diffs should be minimal to quickly see what has changed.

Edit: Seems like it's impossible to permalink to a specific diff on the Gist revisions page. Right now it's the top two revisions.

I might add that this makes `syncing.pokaYokeThreshold` rather useless because I see the warning all the time (e.g. here where actually only 1 line was added).

**Comment by nonoroazoro** [comment]
Thanks! Seems that the order of the extensions is changed, which led to this unexpected diff result. I'll check the diff algorithm see if we could fix it.

**Comment by agross** [comment]
Yes, that what was I thought as well. Perhaps it's possible to sort extensions by id or name.

**Comment by nonoroazoro** [comment]
@agross Yep.

**Comment by nonoroazoro** [comment]
@agross I've released a new version which should have fixed this bug, thanks again for your feedback.

**Comment by agross** [comment]
👍 Seems like my last sync didn't create a huge diff!
