### ISSUE TITLE
[Feature Request] add setting to enable auto sync

### ISSUE THREAD

**Issue by peterschussheim** [nonoroazoro/vscode-syncing#42]
Hi,

Great extension!  One feature currently missing is a setting so that users can 'opt-in' to synchronizing their settings automatically, when they are saved.

Thanks!

**Comment by nonoroazoro** [comment]
@peterschussheim , auto-sync is supported in the [latest release](https://github.com/nonoroazoro/vscode-syncing/releases/latest), enjoy!
