### ISSUE TITLE
Partially works in Portable Mode

### ISSUE THREAD

**Issue by ko-dever** [nonoroazoro/vscode-syncing#43]
### Specifications

* OS Version: macOS High Sierra 10.13.6

* VSCode Version: 1.27.2
**Note :** as mentioned in the title of this issue, I am using VSCode in [Portable Mode](https://code.visualstudio.com/docs/editor/portable).

### Expected Behavior
Seeing [all the settings this extension is supposed to sync](https://github.com/nonoroazoro/vscode-syncing#features), in my Gist.

### Actual Behavior
Only the file `extensions.json` is synced in my Gist.

### Steps to Reproduce

1. Make a fresh install of Visual Studio Code, 
Before doing that, I took care to delete all old folders and files related to my previous install of VSCode (wether in Portable Mode or not) and to reboot my laptop.

2. Edit my User Settings file
Located here `/Applications/code-portable-mode/user-data/User/settings.json`

3. Install your extension, reload VSCode, and configure the extension [as stated in your README](https://github.com/nonoroazoro/vscode-syncing#getting-started).

4. Check my Gist profile and see only the file `extensions.json` is synced.
![vscode syncing issue](https://user-images.githubusercontent.com/4114656/45917244-5a8c0b80-be62-11e8-96ee-5c093096d05f.png)

**Comment by nonoroazoro** [comment]
@ko-dever Sorry, Portable mode is not supported yet~

**Comment by nonoroazoro** [comment]
@ko-dever I think the support for `Portable Mode` will be included in the next release of Syncing~

**Comment by nonoroazoro** [comment]
@ko-dever I've released a new [version](https://github.com/nonoroazoro/vscode-syncing/releases/latest) which should support the Portable Mode.

**Comment by ko-dever** [comment]
That was quick 🙂 .
Everything seems to work perfectly now, thanks !

**Comment by nonoroazoro** [comment]
@ko-dever :)

**Comment by KolyaKorruptis** [comment]
I just got updated to Version: 3.2.6. of Settings Sync on my portable vscode instance.
I uploaded my settings and now the extensions array is completely empty. ;Meanwhile I have about 30 extensions installed.
Before the 3.2.6 update extensions were only noted partly, as described by OP.
