### ISSUE TITLE
Improve startup performance

### ISSUE THREAD

**Issue by fabiospampinato** [nonoroazoro/vscode-syncing#44]
### Specifications

* OS Version: macOS v10.13.5

* VSCode Version: v1.28.1

### Expected Behavior

I think this extension shouldn't activate at all at startup.

If for some reason it really needs to it should be fast. Bundling the extension with webpack will improve the situation massively, you might want to take a look at [this PR](https://github.com/shanalikhan/code-settings-sync/pull/676/files) for an example webpack configuration.

### Actual Behavior

It's quite slow, I'm seeing startup times of about 250ms

### Steps to Reproduce

1. Open VSCode
2. Run `Developer: Startup Performance` from the command palette
3. Check che reported startup times

**Comment by nonoroazoro** [comment]
Good idea! I'll evaluate the performance and see if there’s any room for improvement.

**Comment by nonoroazoro** [comment]
@fabiospampinato Found that the startup time could be reduced to around 100ms by packing the out files. 👍

**Comment by nonoroazoro** [comment]
@fabiospampinato Found that the startup time could be reduced to around 100ms by packing the out files. 👍

**Comment by nonoroazoro** [comment]
@fabiospampinato The latest release ships with this enhancement 😄 , Thanks again and enjoy~

**Comment by fabiospampinato** [comment]
Thank you!
