### ISSUE TITLE
两台电脑之间无法正常同步

### ISSUE THREAD

**Issue by CoolLby** [nonoroazoro/vscode-syncing#45]
### Specifications

* OS Version: Windows10 X64 1803 专业版（两台都是）

* VSCode Version: 1.28.2

### Expected Behavior
- 一台电脑（A电脑）设置上传以后，另一台电脑（B电脑）下载下来，是一模一样的设置，除了排除项

### Actual Behavior
- 上传设置的那台电脑（A电脑）可以正常同步，把设置清空，再下载同步也可以原样下载下来；但是另一台电脑（B电脑）却没有正常同步

### Steps to Reproduce

1. A电脑上传设置
![image](https://user-images.githubusercontent.com/38807139/47150323-d023b400-d308-11e8-9465-542c7117d309.png)
![image](https://user-images.githubusercontent.com/38807139/47150332-d74ac200-d308-11e8-8518-1cfc3852d9c4.png)

2. B电脑下载设置
![image](https://user-images.githubusercontent.com/38807139/47150365-efbadc80-d308-11e8-83d2-01b70eb54161.png)
![image](https://user-images.githubusercontent.com/38807139/47150382-ff3a2580-d308-11e8-89a8-44c61509c21d.png)

3.没有任何变化...
- token和id都是一样的
- B电脑卸载VScode，重新安装以后也不行

**Comment by nonoroazoro** [comment]
你确定是一样的 id 吗？Open syncing settings 看看。。。另外能把你的 gist public 一下我看看吗？

**Comment by CoolLby** [comment]
- 这是我的id和token

![image](https://user-images.githubusercontent.com/38807139/47268042-28afb700-d57e-11e8-932f-2338115b662d.png)
```json
{
    "id": "031f7300224c44af1a57b6fdcea57770",
    "token": "3ec01f8faf3b018524b0af5eadc74b81f3e87251",
    "http_proxy": ""
}
```
@nonoroazoro 
- 我没有公开过gist..图标变成这样是不是就是公开了...
![image](https://user-images.githubusercontent.com/38807139/47268007-be971200-d57d-11e8-87ba-39fb5541e531.png)
- 下面是我的设置，你可以同步看一下，是不是和我的一样...
```json
{
  "editor.acceptSuggestionOnEnter": "off",
  "editor.cursorBlinking": "solid",
  "editor.detectIndentation": false,
  "editor.fontFamily": "'InconsolataLGC NF',  '思源黑体 CN'",
  "editor.fontLigatures": true,
  "editor.fontSize": 15,
  "editor.fontWeight": "400",
  "editor.mouseWheelZoom": true,
  "editor.renderControlCharacters": true,
  "editor.renderWhitespace": "all",
  "editor.tabCompletion": "onlySnippets",
  "editor.tabSize": 2,
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Comments",
        "scope": "punctuation.definition.comment",
        "settings": {
          "foreground": "#DAA569"
        }
      },
      {
        "name": "Meta tag",
        "scope": "meta.tag",
        "settings": {
          "foreground": "#40E0D0"
        }
      },
    ],
    "comments": "#BC8F8F",
  },
  "files.autoSave": "afterDelay",
  "git.enableSmartCommit": true,
  "gitlens.advanced.messages": {
    "suppressShowKeyBindingsNotice": true
  },
  "http.proxy": "http://127.0.0.1:1080",
  "markdown.preview.fontFamily": "'思源黑体 CN', -apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', 'HelveticaNeue-Light', 'Ubuntu', 'Droid Sans', sans-serif",
  "syncing.excludedExtensions": [
    "ms-ceintl.vscode-language-pack-zh-hans",
  ],
  "syncing.excludedSettings": [
    "editor.fontSize",
    "window.zoomLevel",
  ],
  "terminal.integrated.fontFamily": "Consolas",
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "editor.renderIndentGuides": false,
  "git.autofetch": true,
  "guides.active.color.light": "rgba(65, 105, 225, 0.75)",
  "guides.active.color.dark": "rgba(30, 144, 255, 0.75)",
  "guides.active.width": 3,
  "guides.stack.color.light": "rgba(63, 89, 171, 1)",
  "guides.stack.color.dark": "rgba(61, 89, 171, 0.75)",
  "guides.normal.color.light": "rgba(8, 46, 84, 1)",
  "guides.normal.color.dark": "rgba(8, 46, 84, 0.75)",
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 0.8,
  "workbench.colorTheme": "One Dark Pro Vivid",
  "workbench.colorCustomizations": {
    "activityBarBadge.background": "#00BCD4",
    "list.activeSelectionForeground": "#00BCD4",
    "list.inactiveSelectionForeground": "#00BCD4",
    "list.highlightForeground": "#00BCD4",
    "scrollbarSlider.activeBackground": "#00BCD450",
    "editorSuggestWidget.highlightForeground": "#00BCD4",
    "textLink.foreground": "#00BCD4",
    "progressBar.background": "#00BCD4",
    "pickerGroup.foreground": "#00BCD4",
    "tab.activeBorder": "#00BCD4",
    "notificationLink.foreground": "#00BCD4",
    "editorWidget.resizeBorder": "#00BCD4",
    "editorWidget.border": "#00BCD4",
    "settings.modifiedItemIndicator": "#00BCD4",
    "settings.headerForeground": "#00BCD4",
    "panelTitle.activeBorder": "#00BCD4",
    "breadcrumb.activeSelectionForeground": "#00BCD4",
    "menu.selectionForeground": "#00BCD4",
    "menubar.selectionForeground": "#00BCD4",
  },
  "workbench.iconTheme": "vscode-great-icons",
  "workbench.statusBar.feedback.visible": false,
  /**
  "workbench.colorCustomizations": {
    "sideBar.background": "#292c35",
    "sideBar.border": "#252525",
  }
  **/
}
```

**Comment by CoolLby** [comment]
@nonoroazoro 
- 本来是想重新生成一个token的...结果又发现了一个小问题...
- 输入token以后，会提示token不存在，等待了十分钟再次输入，还是提示不存在
![1](https://user-images.githubusercontent.com/38807139/47280790-a28d8200-d60a-11e8-8d17-69cccc0bf7e8.gif)

**Comment by nonoroazoro** [comment]
@CoolLby 我测试过你发的配置了，下载之后和你的完全一致，没有任何区别的。

**Comment by nonoroazoro** [comment]
你输入错了，第一个动图，对话框需要你输入的是 Gist 的 ID，也就是这里的 id（你输入的是 Token）。

**Comment by CoolLby** [comment]
@nonoroazoro
- 菊苣你也太敬业了.... 怪我太小白了...
- 现在我A电脑（台式机）已经重新设置了token和id，也已经正常上传了设置
- B电脑（笔记本）重新安装vscode，安装syncing，输入token.和id，设置我看已经下载下来了，和台式机一模一样，但是卡在【1/44】一个钟头了，我是继续等还是...
![snipaste_2018-10-22_22-30-02](https://user-images.githubusercontent.com/38807139/47298533-a4773580-d64a-11e8-9f15-54a8a32a226a.png)
- 因为我路由器端已经设置了翻墙，电脑没开代理，所以vscode也就没设置，我网速绝对可以！！！
![image](https://user-images.githubusercontent.com/38807139/47298678-fae47400-d64a-11e8-9a33-4415e081ea45.png)
- 代理是撸的GCP的羊毛，速度也可以的...所以网速没问题
- 但它卡在这里，我能做些啥呢...

- 这一步的的意思 是在"在下拉列表选择id"或者"选择在下一步手动输入id"对吧...我在这也卡了一下, 我好笨...
![image](https://user-images.githubusercontent.com/38807139/47298870-71817180-d64b-11e8-9325-e39f1afe28b4.png)

**Comment by nonoroazoro** [comment]
@CoolLby 哈哈，没关系，卡住在国内是难免会遇到的情况。我看你的描述应该是配置文件都下载成功了，但是插件没有下载成功？我怀疑还是网络问题。

关于你贴出来的下拉列表选择，这个列表展示的是你 GitHub Gist 中当前所有已同步的配置，你可以任意选择一个 ID，之后 Syncing 就会记住这个 ID，你的本地和远端就会用这个 Gist 来同步配置了。

网络问题的话，其实是最麻烦的，很难确定到底是哪的问题，或者你也可以试试在路由器中把 VSCode 的网络请求分配为直接连接（不走代理）试试。

**Comment by CoolLby** [comment]
@nonoroazoro 
- 卡住我就退了，重载继续下，就这么断断续续下完了...
- 现在使用正常
