### ISSUE TITLE
Error: Cannot read property 'toLocaleLowerCase' of undefined

### ISSUE THREAD

**Issue by zsy619** [nonoroazoro/vscode-syncing#46]
### Specifications

* OS Version:
版本 1809（os内部版本 17763.55）
* VSCode Version:
1.29.0

### Steps to Reproduce

同步提示：cannot read property 'toLocaleLowerCase' of undefined

**Comment by nonoroazoro** [comment]
@zsy619 我尝试修正了一处空值错误，新版本已经发了，你可以再试试~
