### ISSUE TITLE
Syncing multiple extensions / manual reloads required between installing each.

### ISSUE THREAD

**Issue by JohnLBevan** [nonoroazoro/vscode-syncing#48]
### Specifications

* OS Version: Windows 10 EE 10.0.17134
* OS Version: Windows 17 Pro 6.1.7601 SP1

* VSCode Version: 1.29.1 (user setup)

### Expected Behavior
When running DOWNLOAD all extensions from the definition file should be installed.

### Actual Behavior
Some extensions are installed, but others may be queued until VSCode is restarted.

i.e. the extension works well, but it seems that some extensions block others from being installed until a VS Code restart/reload occurs.  It would be helpful if SYNCING could either automatically perform the reloads as required, or could alert the user that the sync could not be completed until a restart.  
Failing that, just adding a note on this to the [Getting Started](https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing#user-content-getting-started) page would be helpful

It's a minor issue, easily worked around, but I spent a while wondering why it wasn't working since the extension which prompted me to seek and add this extension wasn't synced on first use, so at first I assumed nothing had happened, as I'd not noted what other extensions had been impacted.

### Steps to Reproduce

1. From machine A install extensions: 
 * [Azure Repos](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team)
 * [C#](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)
 * [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
2. Run UPLOAD on machine A
3. Run DOWNLOAD on machine B

---

ps. Thank-you for making and sharing this extension; love it.

**Comment by nonoroazoro** [comment]
I'll look into it~

**Comment by nonoroazoro** [comment]
@JohnLBevan In vanilla VSCode, whenever you **installed/updated/removed** any extension, **a reload is required** for the changes to take effect, and you'll be **prompted** so that the changes will **never interrupt** your current work. 

I quite like this design principle, so that the Syncing's behavior is really just the same as VSCode, and I don't think reloading/restarting the VSCode automatically is a good idea...

**Comment by JohnLBevan** [comment]
Makes sense; thanks.

FYI: As of the latest version of VSCode, reloads are no longer required, so this issue is resolved: https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

**Comment by nonoroazoro** [comment]
@JohnLBevan That's a great feature :). But it seems that there are certain extensions that still require reload, maybe I should keep the status quo until I figure out how the `extensions.onDidChange` works.
