### ISSUE TITLE
Compatibility with VS-Codium

### ISSUE THREAD

**Issue by Backfighter** [nonoroazoro/vscode-syncing#49]
### Specifications

* OS Version: Windows 10 (1709)

* VSCode Version: 1.30.2

### Expected Behavior

When syncing extensions should be installed for [VSCodium](https://github.com/VSCodium/vscodium) and settings should be written to the correct folder.

### Actual Behavior

Extensions are installed to `${HOME}/.vscode` (VSCodium uses `${HOME}/.vscode-oss`) and settings are stored to `${APPDATA}/Code/User` (VSCodium uses `${APPDATA}/VSCodium/User`).

### Steps to Reproduce

1. Install VSCodium.

1. Download perviously uploaded settings/extensions/keybindings using syncing.

This can be easily solved by making the paths configurable.

**Comment by nonoroazoro** [comment]
@Backfighter I've found a way to identify the running binary version of VSCode, and will release in the next version after testing.

**Comment by Backfighter** [comment]
Wow thank you very much for the quick response. Love your project, especially because it's so well structured.

**Comment by nonoroazoro** [comment]
Haha, I’m so glad you like it. BTW, i've released the new version, enjoy!

**Comment by Backfighter** [comment]
Thank you again. I've just installed your new version and everything work perfectly!

**Comment by nonoroazoro** [comment]
All right :)
