### ISSUE TITLE
问个比较蠢的问题

### ISSUE THREAD

**Issue by CyshallChan** [nonoroazoro/vscode-syncing#5]
之前用的是ATOM，获取了GistID和Token后直接设置就可以同步了。
VSCode安装了你这个插件同步设置，但是不是很清楚怎么设置。
找到了如下图的插件的初始配置，好像是要求有自己的服务器？
![image](https://cloud.githubusercontent.com/assets/22564041/25092690/696b87a8-23c1-11e7-84d6-d45dce20504e.png)
问题比较蠢，希望作者不要介意:(

**Comment by nonoroazoro** [comment]
@CyshallChan 貌似你用的不是我写的插件。。。

[Syncing](https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing) 本身只需要 GitHub Token 就能工作了，实际上你除了可以设置代理（翻墙）之外，不需要也没有任何其他配置。

**Comment by CyshallChan** [comment]
@nonoroazoro 我是在微软的插件页面跳转到GitHub上的，应该是你的插件，名字是一样的。
在命令窗口输入upload提示没有连接，如下图：
![image](https://cloud.githubusercontent.com/assets/22564041/25111694/16df8030-241f-11e7-9e46-f02483fbb303.png)
没出现你说的菜单选项。

**Comment by nonoroazoro** [comment]
@CyshallChan 没关系，你看下图：
![snip20170418_2](https://cloud.githubusercontent.com/assets/383132/25111883/4e393390-2420-11e7-8d82-08ac6e5d7b01.png)

但是你截图中的所有配置项都跟 Syncing 插件没有任何关系，都是其他插件的配置信息。

**Comment by CyshallChan** [comment]
@nonoroazoro 
![image](https://cloud.githubusercontent.com/assets/22564041/25111953/bf3475be-2420-11e7-833c-bde2699f7005.png)
果然是我装错插件了（囧），真的不好意思：(
最后，感谢回答！

**Comment by nonoroazoro** [comment]
@CyshallChan 哈哈，没有关系！ 😸
