### ISSUE TITLE
Feature Request:  Add "Sync Needed" alert

### ISSUE THREAD

**Issue by mpearon** [nonoroazoro/vscode-syncing#53]
### Specifications

* OS Version: Windows 10 / Mac OS X Mojave

* VSCode Version: 1.31.1 (1.31.1)

I have seen requests to add an auto-sync, but I think an option to just alert if the Gist content is newer than what is loaded might be good as well.  Perhaps a "Settings Sync Needed" toast?

**Comment by nonoroazoro** [comment]
Hmm, sounds interesting.

**Comment by cig0** [comment]
Nice idea!

**Comment by mbaas2** [comment]
+1 from me. I think this would be a great step towards "real" (automatic) syncing!

**Comment by nonoroazoro** [comment]
@mpearon @cig0 @mbaas2 , auto-sync is supported in the [latest release](https://github.com/nonoroazoro/vscode-syncing/releases/latest), enjoy!
