### ISSUE TITLE
Syncing: uploading failed. Not found

### ISSUE THREAD

**Issue by mubaidr** [nonoroazoro/vscode-syncing#54]
### Specifications

* OS Version: Windows 10

* VSCode Version: 1.21 (system setup)

### Expected Behavior
Setting should be uploaded

### Actual Behavior
Setting failed to upload, with error: 
```bash
syncing: uploading failed. Not found
```

![capture](https://user-images.githubusercontent.com/2222702/53221035-5e43da00-361c-11e9-9ec6-926c1b7011ff.PNG)
![capture1](https://user-images.githubusercontent.com/2222702/53221037-60a63400-361c-11e9-9feb-bf19021f715a.PNG)

### Steps to Reproduce

Not sure.

**Comment by aloneZERO** [comment]
I have the same problem. :face_with_head_bandage:

**Comment by nonoroazoro** [comment]
This error log is just a warning, actually it is ignored inside Syncing. Therefore, theoretically, this error will not stop the uploading. But it's sure that something is broken, I'll check.

**Comment by nonoroazoro** [comment]
@mubaidr Is it convenient to share your settings Gist?

**Comment by mubaidr** [comment]
Sure, please: https://gist.github.com/mubaidr/16f99a134d0f701e3b29cecce450bb9c

**Comment by nonoroazoro** [comment]
@mubaidr Thanks!

**Comment by mubaidr** [comment]
I forgot to mention that on one PC this works fine. But on PC with proxy server connection, this fails. I don't know if the extensions fails due to proxy or not. Proxy server is authenticated. It used to work before. (VS-CODE can connect to Internet fine)

**Comment by nonoroazoro** [comment]
@mubaidr That makes sense~ I'll also check the connection issue.

**Comment by nonoroazoro** [comment]
@mubaidr After many attempts, still cannot reproduce the failure 🤣.

**Comment by mubaidr** [comment]
Maybe it is because the proxy requires authentication. Previously it worked fine with un-authenticated proxy.

**Comment by nonoroazoro** [comment]
@mubaidr Unfortunately, I don't have any authenticated-proxy for testing. Sorry for the inconvenience.

**Comment by mubaidr** [comment]
@nonoroazoro I am still having the same issue. All the vscode functionality requiring internet works fine but syncing does not work. It can successfully connect, I know because it warns about too many changes when uploading but then it fails giving the same error that file `local.json` not found. 

Can you please check if you have this file in the path mentioned by the error message?

**Comment by mubaidr** [comment]
An update: I ran command change language in `vscode` command pallet and chose default language. Now the `locale.json` file is created. But the syncing issue remains.

**Comment by mubaidr** [comment]
Can you please try and identify which lines of code print this message: `uploading failed. Not found`

**Comment by nonoroazoro** [comment]
@mubaidr I'll check it~

**Comment by mubaidr** [comment]
So finally it is working now. Problem seems to be with the Github token. Once I changed the github token it worked fine. 🤦‍♂ 

But still I would say that error message might be needed to updated.

**Comment by nonoroazoro** [comment]
Great! I'll tweak the error msg asap~

**Comment by mubaidr** [comment]
Looks like the there was no permission for `gist` 🤦‍♂

**Comment by nonoroazoro** [comment]
Hmm... I'll make a test!

**Comment by nonoroazoro** [comment]
@mubaidr New version is released, should have fixed the message.
