### ISSUE TITLE
不能共享public的gist了

### ISSUE THREAD

**Issue by songgnqing** [nonoroazoro/vscode-syncing#55]
年前还是可以的，年后就没法把把我的配置共享给其他人了

提示：
![image](https://user-images.githubusercontent.com/16859253/53756306-c2f01600-3ef3-11e9-8308-aca4bd55d958.png)

**Comment by nonoroazoro** [comment]
@songgnqing 应该不是插件本身的问题，请检查 Gist 是否正确设置为 Public，你的朋友是否使用了正确的 Gist ID。

**Comment by songgnqing** [comment]
确认是public的。而且年前是可以的用的，同一个gist id。

**Comment by nonoroazoro** [comment]
我来检查一下什么问题吧。

**Comment by nonoroazoro** [comment]
@songgnqing 貌似是我之前更新的一个第三方 Github API 导致的问题。

**Comment by nonoroazoro** [comment]
@songgnqing 新版本发布了，已修复这个问题。
