### ISSUE TITLE
Feature Request:  Coder.com Support

### ISSUE THREAD

**Issue by mpearon** [nonoroazoro/vscode-syncing#56]
It would be nice to have support for Coder.com for this extension.
I've seen that [Settings Sync](https://github.com/shanalikhan/code-settings-sync ) has recently added the feature.

![image](https://user-images.githubusercontent.com/7157790/55109417-d54d1200-50a3-11e9-90d6-e8190a63f582.png)

**Comment by nonoroazoro** [comment]
@mpearon I'll check it out, but this may take some time as I've been so busy recently... :)

**Comment by nonoroazoro** [comment]
@mpearon After some digging, I'd rather say this codercom edition is much more like a toy than a production-ready ide. It lacks lots of VSCode standard api, especially the extension-related api.

Thus, there's no way to support this edition right now, and I seriously doubt that the Setting Sync has supported this edition... 😭

**Comment by mpearon** [comment]
Completely understand.  Hopefully they'll get it up to par, because I can see where it could be handy!
Oh, really?  I was basing that off of GitHub tickets, so it's entirely possible that it was false.  I tore down my Settings Sync stuff in favor of Syncing (the cross-platform actually worked!), so I never actually tested.

I appreciate you taking the time to investigate! :)

**Comment by nonoroazoro** [comment]
@mpearon I'd not close this issue and I'm sure I will add this feature when the coder edition is ready~, and thanks a lot for your feedback! :smile:
