### ISSUE TITLE
Uploading/Downloading does not reproduce exact environment

### ISSUE THREAD

**Issue by mbaas2** [nonoroazoro/vscode-syncing#57]
### Specifications

* Sync from (1):
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

* Sync to (2):
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-17-generic snap

### Expected Behavior
After uploading settings from (1) and downloading into (2) I had expected to see the same extensions as in the original system.

### Actual Behavior
(1) uses an extension "[Favorites Manager](https://github.com/oleg-shilo/Favorites.vscode)".  (2) did not show that (even after a restart), but did show "[Favorites](https://github.com/kdcro101/vscode-favorites). I don't know if FM wasn't installed at all and F wasn't wiped out (I had used it before in that installation). Other extensions are missing, too - and extension that I had disabled in (1) are still active in (2).

**Comment by nonoroazoro** [comment]
@mbaas2 I tried the extensions you listed, all of them were synced correctly. So maybe you have to check the followings:
1. Reload the VSCode after you install the extensions (although VSCode has already supported no reloading on installing extensions, while it's API seems hasn't);
1. Upload the settings on (1)
1. Try to download settings on (2), and make sure you download from the same Gist (with the same ID).
1. Check whether the synchronization has been successful.

If the issue still occurs, please send me the edition of your Linux Distribution together with its version.
I'm sorry for the inconvenience.

**Comment by cig0** [comment]
Hi all,

@nonoroazoro I was about to open a ticket with an issue that I think might be related to the behavior seen by @mbaas2:

_Syncing seems to only sync *enabled* extensions, not all the installed extensions._

How to reproduce the issue:

1. Install a couple of extensions and disable one of them
2. Upload your settings
3. On target VSC, download the settings and see if the two extensions you just installed on the source VSC are present, or just the one that was enabled at the time of the syncing.

Let me know what you think.
Thanks!

**Comment by nonoroazoro** [comment]
@cig0 You're right, Syncing does only sync the enabled extensions. The fact is, VSCode doesn't expose any api to get the `disabled extensions` ([#14444](https://github.com/Microsoft/vscode/issues/14444)), which means we have no way to sync the disabled extensions at present.

**Comment by cig0** [comment]
Oh I see, thanks for the additional info, I'll monitor that issue.

**Comment by cig0** [comment]
@nonoroazoro Can this https://github.com/Microsoft/vscode/issues/14444#issuecomment-462305821 help?

**Comment by nonoroazoro** [comment]
@cig0 Unfortunately that doesn't help...

**Comment by cig0** [comment]
Thanks, I'll raise the issue in the main thread then and keep you updated
