### ISSUE TITLE
Issues while installing extensions

### ISSUE THREAD

**Issue by sandy081** [nonoroazoro/vscode-syncing#58]
One of the users reported us that he is seeing Node Debug extension twice and is actually seen in user extensions folder. After investigating, I suspect that this extension which does synchronisation of extension, could be installing the Node debug extension. This is a built in extension and should not be installed. I have also noticed that this extension installs an extension from market place by itself. There are following issues with it

1. Could lead to corrupted installation when the window in which you are installing is closed or reloaded or crashed. 

2. Could be error prone by missing some scenarios like built in extensions

3. If the extension is uninstalled, extracting the same extension does not work.

There could be more such scenarios and behaviours which VS Code would have already taken care of while installing. 

So I would suggest to use the command `workbench.extensions.installExtension` to install an extension instead of doing it by yourself - Ref: https://github.com/Microsoft/vscode/issues/70468

**Comment by nonoroazoro** [comment]
@sandy081 I'll look into it.

**Comment by nonoroazoro** [comment]
@sandy081 I've confirmed that Syncing will never touch the built-in extensions, so I don't think this is caused by Syncing.

As for the installation of the extensions you mentioned, that's right and I‘ve already planned to replace with the install command of VSCode~
