### ISSUE TITLE
Feature Request: Give the gist id a name when creating a new one and show this name in the github gist and in the list when uploading/downloading settings

### ISSUE THREAD

**Issue by phloose** [nonoroazoro/vscode-syncing#59]
I like very much the possibility to choose between different gist ids to sync with. It would be awesome if you could give them a name to make it more easy to manage multiple gist (e.g. Home, Office, Device1, Device2, how you like...).

In this way the name should be given when creating a new gist id and should be shown in the gist description in github, to easily identify it. Also, as written in the title, it should show up when uploading/downloading settings together with the gist id.

Keep up the good work!

**Comment by nonoroazoro** [comment]
@xibalba01 Good idea!
