### ISSUE TITLE
之前可以使用码云的（gitee.com），为什么现在不能了呢，提示必须使用github

### ISSUE THREAD

**Issue by CatchLife** [nonoroazoro/vscode-syncing#60]
之前可以使用码云的（gitee.com），为什么现在不能了呢，提示必须使用github

**Comment by nonoroazoro** [comment]
不可能啊，从来没支持过 Gitee ...

**Comment by CatchLife** [comment]
我上一次用是一年前左右吧，当时记得用的gitee，还看到了当时创建的私人令牌，也可能当时你这个项目是无心插柳恰好支持了gitee，不过国内github不太稳定，有时候成功有时候失败的，速度没有gitee快，这个能支持下吗

**Comment by nonoroazoro** [comment]
这倒是有可能的。不过现在插件依赖的 GitHub API 是由第三方提供的，不太清楚支持起来麻不麻烦，我回头看看。

**Comment by nonoroazoro** [comment]
@CatchLife 为了不让 Syncing 的配置过程变得过于复杂，码云将来应该不会被支持，实在抱歉。
