### ISSUE TITLE
Questions about auto sync option

### ISSUE THREAD

**Issue by xibalba01** [nonoroazoro/vscode-syncing#61]
I have questions about the auto sync option: 

* Does it detect changes between the actual setting and the configured gist and either uploads or downloads settings?
* Or does it just upload settings on every startup? 

I'm asking because i use the same setup on 3 different devices and if it would just upload the settings on every startup it would overwrite the settings i made before on another device...

Thanks for your nice extension. It does what it should and is not overloaded like settings-sync,

**Comment by nonoroazoro** [comment]
@xibalba01 

1. First, it will check the differences between the local and remote settings.

1. Second, it will check the `last modified time` of the settings which leads to different actions:

    1. If the local settings are newer -> Upload settings.

    1. If the remote settings are newer -> Download settings.

1. And finally, it will show a confim dialog if there're too many changes since the last synchronization.

**Comment by xibalba01** [comment]
Thank you for the clarification! Nice feature, exactly what i needed!

By the way i really like this extension! I switched from settings sync to your extension mainly because it has the chance to exclude settings and also because it has less commands attached (only upload, download and settings). Like said above, it does what it should do, and does it very well!

**Comment by nonoroazoro** [comment]
@xibalba01 I'm very glad you like it :)
