### ISSUE TITLE
Bug: Auto Sync - Two connected devices think they both have the newest settings and upload, thus overwritting the "newer" setting

### ISSUE THREAD

**Issue by phloose** [nonoroazoro/vscode-syncing#63]
### Specifications

* OS Version: Windows 10 1809

* VSCode Version: 1.36.1 (system setup)

* Syncing version: 3.0.5

### Expected Behavior

**Auto-sync:** Install an extension or change a setting in VSCode on a first device, it gets automatically updated and when starting VSCode on a second device automatically downloads the newer settings just uploaded. When an extension gets updated on the first device upload the corresponding setting, on the second device, wait until the update process for extensions has completed and THEN check 
if the settings are different and upload/download/do nothing.

### Actual Behavior

**Auto-sync:** It can occasionally happen, that after installing an extension or changing a setting followed by syncing automatically on a first device, the second device will also make an attempt to upload its settings automatically. This happens especially when extension updates happen just after VSCode start. So somehow syncing see's changes on the second device, that are newer than the previously updated settings from the first device even if that first device has already an updated extension or a newer setting. It comes to my mind that maybe during the update process it alters the settings.json/extensions.json so that the modified date seems younger than upstream?!? At the end the result is that after starting the second device the "newer" settings upstream are "overwritten" with e.g. and older version for an extension. I have the feeling that the update process of VSCode itself has something to do with that and somehow confuses syncing while checking the settings status. 

Suggestion: Wait a little longer for checking differences between settings so that VSCode has enough time to update extensions?!

### Steps to Reproduce

* Connect two devices to a gis
* Make changes or download an extension on the first device
* Start VSCode on a second device
* It can happen, that the "newer" settings with the newer extension version will be overwritten by the sync process from the second deivce

**Comment by nonoroazoro** [comment]
Hmm, maybe the VSCode modified the settings while updating the extensions, I'll check it out.

**Comment by nonoroazoro** [comment]
@xibalba01 Did you run Syncing on the two devices simultaneously?

**Comment by xibalba01** [comment]
@nonoroazoro No not really. Normally i used vscode on one device at a time and at another time the other. It could happen, and that was during the initial time of setting up my different vscode, that i had it open at the same time, if this is what you mean. But the normal case was like described, doing some work on one device, changing a setting/adding an extension, then at a later point using the other device... And that was the point where the second device sometimes uploaded also its settings, even though the first device had "newer" settings.

**Comment by nonoroazoro** [comment]
@xibalba01 The auto-sync functionality is relying on the clocks of your devices, but Syncing is currently unable to [synchronize the clocks](https://en.wikipedia.org/wiki/Clock_synchronization) between different devices, which may lead to misjudgment of `last modified time` and trigger unexpected settings synchronization.

Sadly, I cannot guarantee that I can fix it...

**Comment by xibalba01** [comment]
Ok but thank you very much for your investigation! Still like very much your great extension! I turned off the auto-sync for the moment and am now using a manual workaround... At the start of each session i download my settings and at the end i upload it :)

What about using the difference between modification time of local settings and upload time of the gist settings? Would that circumvent the clock sync issue? Because when you upload something it is very likely that something has changed and if the modification time of the local settings on a different device is older than this gist modification it should get the younger settings from the gist.

**Comment by nonoroazoro** [comment]
In fact, Syncing is already using the `local last modified time` and `remote gist last update time`. But since the clocks are not synchronized between the devices (including GitHub's clock), we still cannot precisely determine the last modified time.

**Comment by xibalba01** [comment]
Ah i see, thanks for the clarification

**Comment by nonoroazoro** [comment]
I'll dig into it, and hope we can find a solution :)

**Comment by nonoroazoro** [comment]
@xibalba01 I've released a new version, which improved the auto-sync process. You should try it~
