### ISSUE TITLE
Constantly asks for access token

### ISSUE THREAD

**Issue by oliversalzburg** [nonoroazoro/vscode-syncing#64]
### Specifications

* OS Version: Windows 10

* VSCode Version: 1.36.1

### Expected Behavior
I enter the access token and am never asked for it again without good reason.

### Actual Behavior
I am constantly asked for the access token for no apparent reason.

### Steps to Reproduce
I don't know. This didn't happen last time I was using VS Code and the extension doesn't tell me what the problem is.

`auto_sync` is not enabled. `token` is set and valid. Extension asks for token about every minute. When I enter my token or not, shortly after I see "Syncing: Settings uploaded" in the status bar.

**Comment by nonoroazoro** [comment]
You mean the extension asked for the token again and again while you actually did nothing at the meantime?

**Comment by oliversalzburg** [comment]
@nonoroazoro Yes. At least, I couldn't detect what specifically I might have been doing that would cause the behavior.

I later suspected a relation between the behavior and me having multiple instances of VS Code open. But I do that all the time. So it wasn't anything out of the ordinary.

If there is somewhere to look for more information, I'd gladly do it. I couldn't find any output that would help me troubleshoot this.

**Comment by nonoroazoro** [comment]
@oliversalzburg Theoretically, multiple instances of VSCode will not lead to the problem. Syncing actually does nothing unless you turned on the auto-sync or executed some of its commands.

I wonder if it's possible that you delete the `syncing.json` file, re-install the extension and try it again? Thanks!
