### ISSUE TITLE
Error "Uploading failed. Functions are not supported"

### ISSUE THREAD

**Issue by ko-dever** [nonoroazoro/vscode-syncing#65]
### Specifications

* OS Version: macOS Mojave

* VSCode Version: 1.37.0

### Expected Behavior

Be able to upload settings as usual.

### Actual Behavior

When I try to upload my settings I now get this error :

![a](https://user-images.githubusercontent.com/4114656/62783756-fc393d00-bab4-11e9-8bef-fbe576c7a603.png)

I checked all my settings and I don't have anything that looks like a function.

**Comment by nonoroazoro** [comment]
Could you please check if there's any error log in the VSCode console (via Help -> Toggle Developer Tools)

**Comment by ko-dever** [comment]
Absolutely no log :/

![a](https://user-images.githubusercontent.com/4114656/62827756-aa340c80-bbc5-11e9-9558-ce6cf103b877.png)

**Comment by nonoroazoro** [comment]
I tested the extension again on Mac with VSCode 1.37.0, and could not reproduce the issue.
Please re-install the extension and try again.

**Comment by ko-dever** [comment]
I tried to uninstall / install the extension, it did not work.

But I have been able to identify the cause of the problem :
I checked (locally) the files created by your extension on Gist, one by one I commented all their content then I tried to trigger the upload with your extension and it turns out the issue comes from my file `/Applications/code-portable-data/user-data/User/snippets/global.code-snippets` where I have one snippet declared like this :

```js

  // Your extension crash on this line. I have to rename it, which is fine to me.
  // But at least now you know.
  "hasOwnProperty": {

    "description": "obj.hasOwnProperty",
    "scope"      : "javascript,javascriptreact,typescript,typescriptreact",
    "prefix"     : "hop",
    "body"       : [
      "${5:myObj}.hasOwnProperty('${10:propToCheck}')"
    ],
  },
```

**Comment by nonoroazoro** [comment]
@ko-dever Thanks a lot! I'll test the snippet.

**Comment by ko-dever** [comment]
In itself it is not really an issue, the value of the key for each snippet is not reused in VSCode and can be anything (I could have write `"a really great snippet"`).
The most important values are the sub-keys `description`, `scope`, `prefix` and `body`.

**Comment by nonoroazoro** [comment]
@ko-dever I think I find the reason. Syncing is now using a 3rd-party package to diff the changes, which will unexpectedly treat the `hasOwnProperty` as a JavaScript code...

This is actually a bug, I'll try to fix it soon.

**Comment by nonoroazoro** [comment]
@ko-dever I've released a new version which fixed this issue, you can try~
