### ISSUE TITLE
auto-upload-download

### ISSUE THREAD

**Issue by vferko** [nonoroazoro/vscode-syncing#7]
Can we have auto upload on settings change and auto download on startup?

**Comment by nonoroazoro** [comment]
See #6

**Comment by vferko** [comment]
I haven't realized the full implications of auto-upload on each change, that's a very valid argument you provided. Why don't you write this in your md file?

> when you're trying out some new extensions or settings, It will falsely overwrite the Gist of your current settings and this is a nightmare.

**Comment by nonoroazoro** [comment]
@vferko That's a good idea! 😸
