### ISSUE TITLE
Syncing problem when using remote SSH environment.

### ISSUE THREAD

**Issue by medoidai** [nonoroazoro/vscode-syncing#70]
The syncing operation works until 3.0.1 version. From 3.0.2 till 3.0.12 is broken. We would like to upgrade but we need to be able to sync the extensions in a remote environment. We are stick to 3.0.1 version.

### Specifications

* OS Version:

Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

* VSCode Version:

![Screenshot from 2019-12-09 16-26-01](https://user-images.githubusercontent.com/53480868/70443354-a85d5580-1aa0-11ea-94e7-8c03bd3b6eae.png)

### Expected Behavior

Expected behavior is to download all extensions from GitHub Git and after completion a popup to appear in order to reload VSCode.

### Actual Behavior

It loops forever trying to sync the first extension.

![Screenshot from 2019-12-09 16-29-03](https://user-images.githubusercontent.com/53480868/70443558-07bb6580-1aa1-11ea-9016-403e306dcf84.png)

### Steps to Reproduce

1. Install Remote - SSH VSCode extension and connect via SSH to a remote docker container.
2. Install the latest version of Syncing inside the remote docker container.
3. F1+Syncing: Download Settings (enter GIST, etc)

**Comment by nonoroazoro** [comment]
You have to set a proxy in your remote VSCode Syncing settings to make it sync through the proxy from your docker container.

**Comment by medoidai** [comment]
OK! Can't wait to know what happened! Thanks!

**Comment by nonoroazoro** [comment]
@medoidai I rollback the fs-extra to 7.0.1 and published a new version, which may solve the problem.

**Comment by medoidai** [comment]
Problem solved! You are great! Thank you so much!

**Comment by nonoroazoro** [comment]
@medoidai Hoho, that's great! Thanks for your feedback 😄

**Comment by medoidai** [comment]
Merry Christmas!

**Comment by nonoroazoro** [comment]
Yes, you too! My friend.
