### ISSUE TITLE
Removes installed extensions during "Download Settings" that are in Gist

### ISSUE THREAD

**Issue by CUBERLEON** [nonoroazoro/vscode-syncing#89]
### Specifications

* OS Version 1:
   Ubuntu 22.04 LTS

* VSCode Version 1 (older Code):
   Code v1.66.2
   Latest [code-server](https://github.com/coder/code-server) v4.4.0

* OS Version 2:
   Windows 10 x64

* VSCode Version 2 (newer Code):
   Code v1.67.2
   Latest [VSCodium](https://github.com/VSCodium/vscodium) v1.67.2

### Expected Behavior
No changes to the older Code as it already has all the extensions that are in Gist, though some are outdated but latest for the older Code.

### Actual Behavior
Each extension, that has a version in the Gist supported by the never Code but not by the older Code, is silently removed from the older Code. The syncing extension even removes itself (v3.1.0) because v3.2.0 isn't supported at the older Code and the Gist contains v3.2.0.

### Steps to Reproduce

1. Install two Code IDEs of different versions

1. Run "Upload Settings" on the machine with the older Code

1. Run "Download Settings" on the machine with the newer Code

1. Run "Upload Settings" on the machine with the newer Code

1. Run "Download Settings" on the machine with the older Code

My current workaround is to downgrade the newer Code to the version of the older Code. However, once any of the two upgrades, the issue will return.

**Comment by nonoroazoro** [comment]
That's because the extension will check the available extensions for the current VSCode from the MS marketplace and remove the non-existed ones (versions).

I may change the auto-upgrade strategy to provide a better experience for old VSCodes. Thanks for your feedback.

**Comment by nonoroazoro** [comment]
I've published [v3.3.0](https://github.com/nonoroazoro/vscode-syncing/tree/v3.3.0) which will check the latest available version for the current VSCode engine during the synchronization, which should fix your issue.

**Comment by nonoroazoro** [comment]
Also, I've reduced the minimum required VSCode version to `1.37.0` to support older VSCodes.

**Comment by CUBERLEON** [comment]
Thank you!
