### ISSUE TITLE
Extension is missing in gist upload

### ISSUE THREAD

**Issue by femto-code** [nonoroazoro/vscode-syncing#90]
### Specifications

* OS Version: Ubuntu 22.04

* VSCode Version: latest

### Expected Behavior
- All extensions should be uploaded

### Actual Behavior
- `hall.draw-0.1.13` is not synced -> missing in extensions.json in GIST

### Steps to Reproduce

Install extension and try upload

**Comment by nonoroazoro** [comment]
I'll look into it

**Comment by nonoroazoro** [comment]
After some investigation, it appears that the VSCode API doesn't list out this extension, which is quite strange and I have no idea how to fix it yet.
