### ISSUE TITLE
Auto sync firing when saving any document / editor

### ISSUE THREAD

**Issue by femto-code** [nonoroazoro/vscode-syncing#91]
### Specifications

* OS Version: Windows 10

* VSCode Version: latest

### Expected Behavior
- auto syncing on startup

### Actual Behavior
- syncing is triggered when any editor is saved (in my case a simple markdown file)

**Comment by nonoroazoro** [comment]
Auto-sync will only be triggered when your extensions or settings are changed, not startup.
