### ISSUE TITLE
Error on download: Cannot save file extensions.json

### ISSUE THREAD

**Issue by i4004** [nonoroazoro/vscode-syncing#92]
### Specifications

* OS Version:

Windows 10 (latest), Manjaro Linux (latest updates)

* VSCode Version:

1.69.2

The problem appeared after upgrading to 1.69.2 from 1.69.1 (On both OSes)

### Expected Behavior

Settings should be downloaded.

### Actual Behavior

![image](https://user-images.githubusercontent.com/5744532/180618081-fe69f916-3f4f-416b-ac29-f6946de37754.png)

### Steps to Reproduce

1. Run download command under VS 1.69.2

**Comment by i4004** [comment]
I did more tests. The problem is with v3.3.0 of this extension. Downgrade to v3.2.1 solves the problem.

**Comment by nonoroazoro** [comment]
I'll take a look!

**Comment by nonoroazoro** [comment]
@i4004 It seems that the package 'compare-versions' throws the exception, as I added it in the current release to compare the extensions' versions.

**Comment by nonoroazoro** [comment]
A new version has been released to solve this issue, thanks for your feedback!

**Comment by i4004** [comment]
It works now, thank you!

**Comment by nonoroazoro** [comment]
> It works now, thank you!

 my pleasure
